[CmdletBinding()]
param(
    [string]$ProjectRoot = '',
    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
}

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $ProjectRoot 'docs\generated\assembly-map.md'
}

$sourceRoot = Join-Path $ProjectRoot 'Assets\_Project'
$resolvedProjectRoot = [IO.Path]::GetFullPath($ProjectRoot).TrimEnd('\', '/') + [IO.Path]::DirectorySeparatorChar
$asmdefFiles = Get-ChildItem -LiteralPath $sourceRoot -Recurse -Filter '*.asmdef' -File |
    Sort-Object FullName

$rows = foreach ($file in $asmdefFiles) {
    $definition = Get-Content -Raw -LiteralPath $file.FullName | ConvertFrom-Json
    $resolvedFilePath = [IO.Path]::GetFullPath($file.FullName)
    if (-not $resolvedFilePath.StartsWith($resolvedProjectRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Assembly definition is outside the project root: $resolvedFilePath"
    }
    $relativePath = $resolvedFilePath.Substring($resolvedProjectRoot.Length).Replace('\', '/')
    $references = @($definition.references |
        Where-Object { $_ -like 'DigBlocks.*' } |
        Sort-Object -Unique)
    $kind = if ($relativePath -match '(?i)(/Tests/|Tests\.asmdef$)') { 'Test' } else { 'Runtime' }

    [pscustomobject]@{
        Name = [string]$definition.name
        Kind = $kind
        Path = $relativePath
        References = if ($references.Count -eq 0) { '-' } else { $references -join ', ' }
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated assembly map')
$lines.Add('')
$lines.Add('> Generated by `tools/Update-RepositoryMap.ps1` from Unity `.asmdef` files. Do not edit by hand.')
$lines.Add('')
$lines.Add('| Assembly | Kind | Definition | Internal references |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($row in $rows | Sort-Object Kind, Name) {
    $lines.Add("| ``$($row.Name)`` | $($row.Kind) | ``$($row.Path)`` | $($row.References) |")
}
$lines.Add('')
$lines.Add('Only `DigBlocks.*` references are shown; Unity and third-party package references remain authoritative in each `.asmdef`.')

$outputDirectory = Split-Path -Parent $OutputPath
[IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[IO.File]::WriteAllText(
    $OutputPath,
    ($lines -join "`r`n") + "`r`n",
    [Text.UTF8Encoding]::new($false))

Write-Output "Wrote $OutputPath"
